apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t0fs5c0fx-dotnet-basic
  janus-idp.io/tekton: t0fs5c0fx-dotnet-basic
  backstage.io/kubernetes-id: t0fs5c0fx-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: t0fs5c0fx-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
